name: OneBlockSkills
version: '${project.version}'
main: oneblock.skills.Main
api-version: 1.19
authors: [ Mornov ]
description: Custom Skills RPG
depend:
  - ProtocolLib
commands:
  myesha:
    description: Open the Myesha GUI
    usage: /myesha
    permission: myesha.use


